# Уровень журналирования событий
# Может принимать значения: debug, info, warn, error, fatal
loglevel: "info"

# Подключение к Asterisk
asterisk:
  # Адрес сервера телефонии с Asterisk
  host: "localhost"
  # Порт, на котором доступен AMI интерфейс
  port: 5038
  # Имя учетной записи для подключения через AMI
  username: "rt-queue-devstate"
  # Пароль учетной записи для подключения через AMI
  password: "password"
  # Интервал проверки подключения к AMI в секундах
  reconnect: 5